### ISSUE TITLE
Inconsistent error between whois and dns for non existent record

### ISSUE THREAD

**Issue by azimut** [ammario/ipisp#17]
DNS errors, whois resolver returns NA. Particularly difficult to avoid when doing bulk requests in DNS.

I just ended up using whois for my small project.

**Comment by ammario** [comment]
The API was poorly designed to handle per IP failures. I apologize for that...

I intend on fixing this in #18.

For now, unassigned IP addresses are returned as having ASN 0 from the WhoisClient.
