### ISSUE TITLE
Release v2.0.1

### ISSUE THREAD

**Issue by gnuletik** [ammario/ipisp#25]
The last released version (v2.0.0) [was released on Dec 25, 2021](https://github.com/ammario/ipisp/releases/tag/v2.0.0) and does not contain the following fix: https://github.com/ammario/ipisp/pull/23
See https://github.com/ammario/ipisp/compare/v2.0.0...master

This currently requires the use of the `master` branch.

Can you release a new version?

Thanks!

**Comment by ammario** [comment]
Done. See https://github.com/ammario/ipisp/releases/tag/v2.0.1.

**Comment by gnuletik** [comment]
Awesome, thanks!
