### ISSUE TITLE
ASN Name Returns Bad Value

### ISSUE THREAD

**Issue by subfission** [ammario/ipisp#7]
It appears that `ParseName()` has an issue with ASN names using `-`.  The method tokenizes using `-` as a separator, which causes part of the data to be truncated.  Using a slice and then concatenating elements [1+] might be a workable solution...

**Comment by ammario** [comment]
Could you provide an example ASN?

**Comment by subfission** [comment]
Here is an easy one: 

AKAMAI-AS
--
Number | 35993

**Comment by subfission** [comment]
AS35993
Country: US
Registration Date: 2005-05-03
Registrar: arin
Owner: AKAMAI-AS - Akamai Technologies, Inc., US
